"""Distress detection keywords for all 9 supported languages.
Each language has high/medium/low severity keywords."""

distress_keywords = {
    "english": {
        "high": ["want to die", "kill myself", "end my life", "suicide",
                 "can't live anymore", "no reason to live", "better off dead",
                 "hopeless", "can't take this anymore", "dying inside"],
        "medium": ["depressed", "desperate", "suffering", "can't cope",
                   "mental health", "anxiety", "breakdown", "drowning in debt",
                   "lost everything", "overwhelming"],
        "low": ["stressed", "worried", "struggling", "difficult time",
                "tough phase", "hard times", "feeling low"],
    },
    "hindi": {
        "high": ["marna chahta hoon", "jee nahi sakta", "zindagi khatam",
                 "aatmhatya", "nahi jee sakta", "maut chahiye",
                 "jaan de dunga", "zindagi se tang", "sab khatam ho gaya", "khudkhushi"],
        "medium": ["bahut takleef", "haar gaya", "depression",
                   "koi sahara nahi", "seh nahi sakta", "barbaad ho gaya",
                   "dimagi halat", "zindagi bojh", "andhera lag raha hai", "himmat toot gayi"],
        "low": ["tension mein", "pareshani", "mushkil waqt", "chinta", "dukhi",
                "man nahi lag raha", "udaas hoon", "pareshaan hoon", "thak gaya hoon", "bechaini"],
    },
    "tamil": {
        "high": ["saaga virumbukireen", "tharkollai", "vaazha maattaen",
                 "saaganumnu irukku", "ennaal thaanga mudiyalai", "mudichukalaamnu irukkaen",
                 "saavu thaan vazhi", "nimmathiyae illai", "uyira maatha poren", "kaduvaiyaana vali"],
        "medium": ["romba kashtam", "thaanga mudiyalai", "depression",
                   "manasu udainjuruchu", "oru vazhiyum illai", "vazhiyilae illai",
                   "yaarum thunai illai", "nambikkai illai", "romba sogama irukkaen", "manasatchi illai"],
        "low": ["kavalai", "kashta paduren", "tension aa irukku", "kavalaiyaga irukkaen",
                "manasu sariyillai", "bayama irukku", "payama irukku", "thukkama irukku", "yoranai", "payanam"],
    },
    "telugu": {
        "high": ["chachipovalidan anipistundi", "brathakalekapothunna",
                 "aatmahatyha", "chaavali anipistundi", "brathakadam ishtam ledu",
                 "antham chesukuntunna", "jeevitham narakam", "saavali", "prakruthi", "saaya"],
        "medium": ["chala kashta paduthunna", "depression lo unna",
                   "thattukolenu", "okkadini anipistundi", "dikku ledu",
                   "brathuku bharam", "shanti ledu", "bhayam ga undi", "ashanthiga undi", "badha"],
        "low": ["tension ga undi", "kashtanga undi", "worry ga undi",
                "alochanaga undi", "bhayama ga undi", "diguluga undi", "nidra ravadam ledu", "alasi poya", "nirasha", "vishadam"],
    },
    "kannada": {
        "high": ["saaybekku ansirutte", "aatmahathye", "saavu beku",
                 "jeevana beda", "thaaLleekke aagalla", "badukalu ishta illa",
                 "saavu thondee", "jeevana mugisthini", "ella mugiyitu", "yaaru illa"],
        "medium": ["thumba kashta", "depression", "sahisleekke aagalla",
                   "enu maadodu gottilla", "yaaru illa", "manasu odedu hogide",
                   "nambike illa", "khushi illa", "baduku bharavagide", "shanthi illa"],
        "low": ["tension", "kashta aagide", "yochane aagide", "chinte", "badha",
                "bayage", "digilu", "manasilla", "susthu", "nirudyoga"],
    },
    "malayalam": {
        "high": ["marikkanam ennundu", "jeevikkan vayya", "aatmahathya",
                 "maranam venam", "sahikkan kazhiyunnilla", "ellaam avasanippikkunnu",
                 "jeevitham maduthu", "marikkan pova", "uyir kalayum", "gadhiyailla"],
        "medium": ["valare budhimuttanu", "depression",
                   "onninum kazhiyunnilla", "aarum illa", "manasu thakarunnu",
                   "vazhikalillatha", "samshayam", "bhayamaanu", "vedhanayundu", "sankatamanu"],
        "low": ["tension", "budhimutt", "vishamamanu", "pediyundu", "chinthayundu",
                "manasamadhanamilla", "vishramilla", "aswastham", "ashanthi", "alachal"],
    },
    "bengali": {
        "high": ["morte chai", "bacchte chai na", "aatmoghatya",
                 "jiboner kono mane nei", "more jete chai", "ar pari na",
                 "shob shesh", "mora dorkar", "jibon nishphol", "keu nei amar"],
        "medium": ["khub koshto", "depression", "sahya hocche na",
                   "keu nei", "upay nei", "bhorosha nei", "manushik bhashamyu",
                   "andhokar", "shanti nei", "moron tule"],
        "low": ["tension", "chinta", "koshto hocche", "ashanti", "ghabre jacchhi",
                "bhay hocche", "man bhalo nei", "clanto", "osustho", "durdoshay"],
    },
    "marathi": {
        "high": ["maraychay mala", "jgaycha nahi", "aatmahatya",
                 "jeevan nako", "maru dya mala", "sahaan hoat nahi",
                 "shastacha ant", "mrituy hawa", "sagalam sampalam", "himmat nahi"],
        "medium": ["khup kashta", "depression", "sahanshakti sampali",
                   "kaay karaaych kalat nahi", "ekta vatatoy", "bharosa nahi",
                   "manasik traas", "dukhi aahe", "radayla yetay", "upay nahi"],
        "low": ["tension", "kashta", "chinta", "traas", "bhiti vatate",
                "man lagat nahi", "thakaloy", "bechain aahe", "kashatach man nahi", "nervous"],
    },
    "gujarati": {
        "high": ["mari java mangu chu", "jivi nathi shakto",
                 "aatmahatya", "maran joiye", "sahan nathi thatu",
                 "badhu khatam", "mangal thai", "jeevan nathi joiye", "anth aavi gyo", "himmat hari"],
        "medium": ["ghanu kashta", "depression",
                   "shu karvu samjhatu nathi", "koi nathi", "ekla devu",
                   "bharoso nathi", "manasik takleef", "dukh thay che", "rovo aave che", "ashanti"],
        "low": ["tension", "chinta", "mushkeli", "takleef", "bik lage che",
                "man nathi lagtu", "thaki gayo", "bechaini", "adu che", "nirasha"],
    },
}
